ICV_HOME_DIR      = /home/tools/synopsys/icvalidator/U-2022.12
ICV_COORDS_BIT    = 32
WORKING_DIR       = .
INLIB             = lab03
INLIB_PATH        = 
BLOCK             = inverter
CREATE_VUE_OUTPUT = TRUE
PYDB_PATH         = run_details/pydb
RUN_DETAILS_DIR   = run_details
NDB_PATH          = run_details/.ndb
REPORT_LAYOUT_ERRORS = HIERARCHICAL
FORMAT            = OPENACCESS
SCHEMATIC_FORMAT  = ICV
GROUP_PATH        = run_details/group
RUNSET_FILE_NAME  = reference40nm_icv_drc.rs
ENVIRONMENT STRING  PDK_INSTALL_DIR = "/home/dkits/synopsys/m3a"
