compile_mux21:
	dc_shell -f scripts/compile_mux21.tcl

compile_mux21_8bit:
	dc_shell -f scripts/compile_mux21_8bit.tcl

compile_mux21_nbit:
	dc_shell -f scripts/compile_mux21_nbit.tcl


.PHONY: clean
clean:
	-rm -rf ARCH ENTI *.log *.svf *.syn *.mr
