ICV_HOME_DIR      = /home/tools/synopsys/icvalidator/U-2022.12
ICV_COORDS_BIT    = 32
WORKING_DIR       = .
INLIB             = lab03
INLIB_PATH        = 
BLOCK             = inverter
CREATE_VUE_OUTPUT = TRUE
PYDB_PATH         = run_details/pydb
RUN_DETAILS_DIR   = run_details
NDB_PATH          = run_details/.ndb
REPORT_LAYOUT_ERRORS = HIERARCHICAL
FORMAT            = OPENACCESS
SCHEMATIC         = inverter.sch_out.gz
SCHEMATIC_FORMAT  = ICV
GROUP_PATH        = run_details/group
RUNSET_FILE_NAME  = reference40nm_lvs.rs
ENVIRONMENT STRING  PDK_INSTALL_DIR = "/home/dkits/synopsys/m3a"
EXTRACTION_FLOW   = true
WRITE_VUE_INFO    = true
COMPARE_DIR       = run_details/compare
COMPARE_NETLIST_FLOW = ICV
STATUS_COMPARE    = 0
WRITE_EQUIV_NETLISTS = ALL
